ARG BASE_IMAGE
FROM ${BASE_IMAGE}
RUN dnf -y --setopt=install_weak_deps=False install systemd curl git iproute procps-ng hostname util-linux tar && dnf clean all
ENV container=podman
LABEL io.talkchief.kazoo.acceptance="distributed-install-v1"
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
