  - 'Articles':
    - 'Introduction to Storage Plans - S3': 'doc/blog/storage.md'
    - 'Bypass Media Mode': 'doc/blog/bypass_media.md'
    - 'Introduction to Rating and Limits': 'doc/reference/routing.md'
    - 'Call Recording': 'doc/user_guides/call_recording.md'
    - 'Documenting Kazoo': 'doc/blog/documenting_kazoo.md'
    - 'doc/blog/understanding_rates.md'
  - 'Internationalization':
    - 'doc/internationalization/numbers.md'
    - 'doc/internationalization/prompts.md'
    - 'doc/internationalization/examples/dialplan/IE_Local-National-Mobile.md'
    - 'doc/internationalization/examples/dialplan/NL_Amsterdam.md'
    - 'doc/internationalization/examples/dialplan/NL_Rotterdam.md'
    - 'doc/internationalization/examples/number_manager/european_union.md'
    - 'doc/internationalization/numbers/indonesia.md'
  - 'Presentations':
    - 'doc/kazoocon/pivot2014.md'
    - 'doc/kazoocon/pivot2016.md'
    - 'doc/kazoocon/realtime_events2016.md'
  - 'Engineering':
    - 'Getting Started': 'doc/README.md'
    - 'Announcements': 'doc/announcements.md'
    - 'Attachment Handlers Errors': 'applications/crossbar/doc/att_handlers_errors.md'
    - 'Attachments': 'core/kazoo_attachments/README.md'
    - 'Call Recording': 'doc/engineering/call_recording.md'
    - 'Caller ID Formatting': 'doc/reference/caller_id_formatting.md'
    - 'Commits': 'doc/engineering/commits.md'
    - 'Continuous Integration (CI)': 'doc/engineering/ci.md'
    - 'CouchDB Views': 'doc/engineering/couch_views.md'
    - 'Crossbar CSVs': 'doc/engineering/crossbar-csvs.md'
    - 'Documentation':
      - 'How to write docs': 'doc/engineering/documentation.md'
      - 'How to Write Erlang Documentation': 'doc/engineering/erlang-documentation.md'
      - 'Sample API reference doc': 'doc/engineering/things.md'
    - 'Erlang Releases': 'doc/engineering/releases.md'
    - 'Erlang VM Tracing': 'doc/engineering/tracing.md'
    - 'Flame Graphs': 'doc/engineering/flame_graphs.md'
    - 'Install/Build Kazoo': 'doc/installation.md'
    - 'Install/Build Kazoo on MacOS': 'doc/engineering/installing-on-mac.md'
    - 'Getting used to multi-repo': 'doc/getting_used_to_multi_repo.md'
    - 'Kazoo Globals Registry': 'doc/engineering/kz_globals.md'
    - 'Kazoo PropEr':
      - 'applications/properly/doc/README.md'
      - 'applications/properly/doc/rates.md'
      - 'applications/properly/doc/maintenance.md'
    - 'Kazoo Scripts': 'scripts/README.md'
    - 'Loopback Channels': 'doc/engineering/loopback.md'
    - 'Makefile': 'doc/engineering/make.md'
    - 'Property Testing Presentation': 'doc/engineering/property_testing_presentation.md'
    - 'Running Dev Shells': 'scripts/dev/README.md'
    - 'Shipyard': 'doc/engineering/shipyard.md'
    - 'Testing': 'doc/engineering/testing.md'
    - 'Using Dialyzer': 'doc/engineering/dialyzer.md'
    - 'Webhooks': 'doc/engineering/webhooks.md'
  - 'App Exchange':
    - 'doc/appexchange/style_guide.md'
    - 'doc/appexchange/planning.md'
    - 'doc/appexchange/getting_started.md'
    - 'doc/appexchange/intro.md'
    - 'doc/appexchange/sell_faq.md'
    - 'doc/appexchange/build_faq.md'
    - 'doc/appexchange/pricing.md'
    - 'doc/appexchange/support.md'
    - 'doc/appexchange/how_to_sell.md'
    - 'doc/appexchange/submit_app.md'
    - 'doc/appexchange/guidelines.md'
    - 'doc/appexchange/financial_terms.md'
    - 'doc/appexchange/payments.md'
    - 'doc/appexchange/whitelabeling.md'
    - 'doc/appexchange/list_faq.md'
    - 'doc/appexchange/states_workflows.md'
