VSN = case os:getenv("KZ_VERSION") of
          'false' ->
              [C || C <- os:cmd("scripts/next_version 2>/dev/null"), C =/= $\n];
          Version -> Version
      end,

ToName = fun (App) -> list_to_atom(hd(string:tokens(App,"-"))) end,

Apps = [list_to_atom(App)  || "applications/"++App = Dir <- filelib:wildcard("applications/*"), filelib:is_dir(Dir), filelib:is_dir(filename:join([Dir, "ebin"]))],
Core = [list_to_atom(App)  ||         "core/"++App = Dir <- filelib:wildcard(        "core/*"), filelib:is_dir(Dir)],
Deps = [list_to_atom(App)  ||         "deps/"++App = Dir <- filelib:wildcard(        "deps/*"), filelib:is_dir(Dir)],

ToFilterOut = ['.erlang.mk'
              ,'ci.erlang.mk'
              ,'.settings'
              ,'.git'
              ,'.circleci'
              ,skel
              ,parse_trans
              ,meck
              ,'ananke'
              ,'amqp_leader'
              ,elvis_mk
              ],

GetAppFileFun = fun(Prefix, App) ->
                        AppFile = filename:join([Prefix, atom_to_list(App), "ebin", atom_to_list(App) ++ ".app"]),
                        file:consult(AppFile)
                end,

Preparer = fun(List) ->
                   [{App, 'load'} || App <- List,
                                     not lists:member(App, ToFilterOut)
                   ]
           end,
Base = [runtime_tools
       ,tools
       ,wx
       ,observer
       ,debugger
       ,sasl
       ,eunit
       ,common_test
       ],

BASE = [{release
        ,{kazoo, VSN}
        ,Base ++ Preparer(Apps ++ Core ++ Deps)
        }
       ],

ReleaseFun3 = fun(_App, Acc, 'true') -> Acc;
                 (App, Acc, 'false') ->
                      case GetAppFileFun("applications", App) of
                          {ok, [{application, App, Settings}]} ->
                              AppDeps = proplists:get_value(applications, Settings, []),
                              [{release, {App, VSN}, Base ++ Preparer(AppDeps)} | Acc];
                          {'error', 'enoent'} ->
                              io:format('user', "app ~s not compiled, ignoring~n", [App]),
                              Acc;
                          E ->
                              io:format('user', "Error consulting ~s: ~p~n", [App, E]),
                              throw(E)
                      end
              end,

ReleaseFun2 = fun(App, Acc) ->
                      ReleaseFun3(App, Acc, lists:member(App, ToFilterOut))
              end,

APPS = lists:foldl(ReleaseFun2, [], Apps),

Overlay = proplists:get_value(overlay, CONFIG, []),
OTP_VERSON_FILE = filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"]),
OUT_OTP_VERSION_FILE = filename:join(["{{output_dir}}", "releases", "OTP_VERSION"]),
CONFIG_1 = case filelib:is_regular(OTP_VERSON_FILE) of
               'true' ->
                   [{overlay, [{copy, OTP_VERSON_FILE, OUT_OTP_VERSION_FILE} | Overlay]}
                   | [Prop || {K, _}=Prop <- CONFIG, K =/= overlay]
                   ];
               'false' -> CONFIG
           end,

CONFIG_1 ++ BASE ++ APPS.
