VSN = case os:getenv("KZ_VERSION") of
          'false' ->
              [C || C <- os:cmd("scripts/next_version 2>/dev/null"), C =/= $\n];
          Version -> Version
      end,

ToName = fun (App) -> list_to_atom(hd(string:tokens(App,"-"))) end,

Core = [list_to_atom(App)  ||         "core/"++App = Dir <- filelib:wildcard(        "core/*"), filelib:is_dir(Dir)],
Deps = [list_to_atom(App)  ||         "deps/"++App = Dir <- filelib:wildcard(        "deps/*"), filelib:is_dir(Dir)],

ToFilterOut = [rabbitmq_codegen
              ,'.erlang.mk'
              ,'ci.erlang.mk'
              ,'.settings'
              ,'.git'
              ,skel
              ,parse_trans
              ,meck
              ,elvis_mk
              ],
Preparer = fun (List) -> [{E, load} || E <- List, not lists:member(E, ToFilterOut)] end,
Base = [runtime_tools
       ,tools
       ,sasl
       ],

BASE = [{default_release, {kazoo, VSN}}
       ,{release, {kazoo, VSN}
        ,Base ++ Preparer(Core ++ Deps)
        }],

Overlay = proplists:get_value(overlay, CONFIG, []),
OTP_VERSON_FILE = filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"]),
OUT_OTP_VERSION_FILE = filename:join(["{{output_dir}}", "releases", "OTP_VERSION"]),
CONFIG_1 = case filelib:is_regular(OTP_VERSON_FILE) of
               'true' ->
                   [{overlay, [{copy, OTP_VERSON_FILE, OUT_OTP_VERSION_FILE} | Overlay]}
                   | [Prop || {K, _}=Prop <- CONFIG, K =/= overlay]
                   ];
               'false' -> CONFIG
           end,

CONFIG_1 ++ BASE ++ APPS.
