## Makefile that goes in applications/

ROOT = ..

MAKEFILES := $(sort $(wildcard */Makefile))
MAKEDIRS ?= $(MAKEFILES:/Makefile=)

.PHONY: all
all: compile

.PHONY: compile
compile: ACTION = all
compile: $(MAKEDIRS)

.PHONY: compile-lean
compile-lean: ACTION = compile-lean
compile-lean: $(MAKEDIRS)

.PHONY: compile-test
compile-test: ACTION = compile-test
compile-test: $(MAKEDIRS)

.PHONY: compile-test-direct
compile-test-direct: ACTION = compile-test-direct
compile-test-direct: $(MAKEDIRS)

.PHONY: clean
clean: ACTION = clean
clean: $(MAKEDIRS)

.PHONY: clean-test
clean-test: ACTION = clean-test
clean-test: $(MAKEDIRS)

.PHONY: eunit
eunit: ACTION = eunit
eunit: $(MAKEDIRS)

.PHONY: test
test: ACTION = test
test: $(MAKEDIRS)

.PHONY: $(MAKEDIRS)
$(MAKEDIRS):
	$(MAKE) -C $@ $(ACTION)


.PHONY: Makefile
# Ignore Makefile from catch-all target below

%: %
	@$(MAKE) -C $@ $(ACTION)
