# Executed from the applications/ directory so all paths are relative to that

# Don't autopatch applications' Makefiles
# https://erlang.mk/guide/deps.html#_autopatch
NO_AUTOPATCH_ERLANG_MK = 1

ROOT ?= ..
ERLANG_MK_FILENAME = $(wildcard $(ROOT)/erlang.mk)

DEPS_DIR = $(CURDIR)
APPS_MK ?= $(ROOT)/make/apps.mk
MORE_APPS_MK ?= $(ROOT)/make/more_apps.mk

.DEFAULT_GOAL := all

include $(APPS_MK)
-include $(MORE_APPS_MK)
include $(ROOT)/erlang.mk
